[package]
name = "jack_fourier"
version = "0.1.0"
authors = ["user <>"]
edition = "2018"

[dependencies]
dft = "0.5.5"
easyjack = "0.1.2"
nix = "0.7.0"
cairo-rs = "*"
cairo-sys-rs = "*"
gio = "*"

[dependencies.gtk]
version = "0.6.0"
features = ["v3_16"]

